[AVR] Attempt to fix displacement overflow for LDDW/STDW
avr-rust/llvm pull request #4
Opened 2017-09-22 00:19 UTC by exscape

See avr-rust/rust#77.

In some cases, the code generator attempts to generate instructions such as:

lddw r24, Y+63

which expand to:

ldd r24, Y+63
ldd r25, Y+64 # Oops! This is actually ld r25, Y in the binary

This commit limits the first offset to 62, and thus the second to 63.
It also updates some asserts in AVRExpandPseudoInsts.cpp, including for
INW and OUTW, which appear to be unused.

**Please review and test**. I'm not even entirely certain how this fix works, so my faith in it being entirely correct is rather low.

2017-09-23 02:15 UTC, dylanmckay commented
This is a really good catch!

I think the only thing that should be added to this PR is a testcase.

In LLVM, AVR code generator unit tests go into the `test/CodeGen/AVR` folder. The files in here are generally `.ll` files, which represent a textual representation of LLVM's intermediate language.

I think it should be sufficient to compile your reproduction code with Rust again, but pass `--emit llvm-ir` IIRC to generate a `.ll` file. You can then copy-paste the top `RUN:` line from something like `test/CodeGen/AVR/add.ll`, and then add a check like this

```
; CHECK-NOT: ldd r{{[0-9]+}}, {{X|Y|Z}}+64
```

This will ensure that we never emit out of bounds load instructions, ensuring that regexes are used for the registers so that future changes to the register allocator don't make the test fail.

Let me know if you've got any questions :) Thanks for the patch by the way 👌

2017-09-23 10:16 UTC, exscape commented
Thanks :)  
I'm having problems getting tests to run at all. If I simply try to do `llvm-lit test/CodeGen/AVR` (or anything else using llvm-lit) I get errors about lit.site.cfg being missing. `ninja check-llvm` or `make check-llvm` give unknown target errors when run in the LLVM build directory (and elsewhere).

After that, I tried to change rust/src/bootstrap/native.rs to enable the LLVM_BUILD_TESTS option, but when that is "ON" instead of "OFF", I get a ton of build errors immediately when LLVM starts to build.

```
$ mkdir build
$ cd build
$ ../rust/configure --prefix=/opt/avr-rust --prefix=/opt/avr-rust --enable-debug --disable-docs --enable-llvm-assertions --enable-debug-assertions --enable-ninja
[... output ...]
$ time (make -j5 && make install)
[... lots of output ...]
Building LLVM for x86_64-unknown-linux-gnu
running: "cmake" "/home/serenity/rust-avr/avr-rust/rust/src/llvm" "-G" "Ninja" "-DLLVM_ENABLE_ASSERTIONS=ON" "-DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64;Mips;PowerPC;SystemZ;JSBackend;MSP430;Sparc;NVPTX" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_TESTS=ON" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_ENABLE_ZLIB=OFF" "-DWITH_POLLY=OFF" "-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=4" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_INSTALL_PREFIX=/home/serenity/rust-avr/avr-rust/build/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_BUILD_TYPE=Release"
[... most configure output looks good ...]
-- Constructing LLVMBuild project information
-- Targeting X86
-- Targeting ARM
-- Targeting AArch64
-- Targeting Mips
-- Targeting PowerPC
-- Targeting SystemZ
-- Targeting JSBackend
-- Targeting MSP430
-- Targeting Sparc
-- Targeting NVPTX
-- Targeting AVR
-- Configuring done
CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
  The dependency target "llvm-xray" of target "check-all" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:906 (add_lit_target)

CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
  The dependency target "llvm-xray" of target "check-llvm-tools-sanstats"
  does not exist.
Call Stack (most recent call first):
  cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
  test/CMakeLists.txt:150 (add_lit_testsuites)

[... hundreds or thousands of similar lines left out ...]

CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
  The dependency target "llvm-xray" of target
  "check-llvm-codegen-mips-fast-isel" does not exist.
Call Stack (most recent call first):
  cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
  test/CMakeLists.txt:150 (add_lit_testsuites)


CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
  The dependency target "llvm-xray" of target
  "check-llvm-transforms-instcombine" does not exist.
Call Stack (most recent call first):
  cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
  test/CMakeLists.txt:150 (add_lit_testsuites)


-- Generating done
-- Build files have been written to: /home/serenity/rust-avr/avr-rust/build/build/x86_64-unknown-linux-gnu/llvm/build
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/serenity/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617
note: Run with `RUST_BACKTRACE=1` for a backtrace.
        finished in 9.631
Build completed unsuccessfully in 0:01:09
make: *** [Makefile:24: all] Error 101

real    1m9.769s
user    1m59.131s
sys     0m8.528s
```

2017-09-23 10:37 UTC, dylanmckay commented
Within the last week, I recall a message to the llvm-dev mailing list.

there have been a bunch of changes in the area. make sure you are calling
bin/llvm-lit instead of the llvm-lit.py in the source tree.

failing that, a similar problem on the llvm buildbots was fixed by clearing
and recreating the source and build folders

also, you can ignore all of the x-ray errors, I get them periodically but
even though they're errors, makefiles are still created successfully

ignore my typing, am currently on mobile

On 23/09/2017 10:16 pm, "Thomas Backman" <notifications@github.com> wrote:

> Thanks :)
> I'm having problems getting tests to run at all. If I simply try to do llvm-lit
> test/CodeGen/AVR (or anything else using llvm-lit) I get errors about
> lit.site.cfg being missing. ninja check-llvm or make check-llvm give
> unknown target errors when run in the LLVM build directory (and elsewhere).
>
> After that, I tried to change rust/src/bootstrap/native.rs to enable the
> LLVM_BUILD_TESTS option, but when that is "ON" instead of "OFF", I get a
> ton of build errors immediately when LLVM starts to build.
>
> $ mkdir build
> $ cd build
> $ ../rust/configure --prefix=/opt/avr-rust --prefix=/opt/avr-rust --enable-debug --disable-docs --enable-llvm-assertions --enable-debug-assertions --enable-ninja
> [... output ...]
> $ time (make -j5 && make install)
> [... lots of output ...]
> Building LLVM for x86_64-unknown-linux-gnu
> running: "cmake" "/home/serenity/rust-avr/avr-rust/rust/src/llvm" "-G" "Ninja" "-DLLVM_ENABLE_ASSERTIONS=ON" "-DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64;Mips;PowerPC;SystemZ;JSBackend;MSP430;Sparc;NVPTX" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_TESTS=ON" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_ENABLE_ZLIB=OFF" "-DWITH_POLLY=OFF" "-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=4" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_INSTALL_PREFIX=/home/serenity/rust-avr/avr-rust/build/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_BUILD_TYPE=Release"
> [... most configure output looks good ...]
> -- Constructing LLVMBuild project information
> -- Targeting X86
> -- Targeting ARM
> -- Targeting AArch64
> -- Targeting Mips
> -- Targeting PowerPC
> -- Targeting SystemZ
> -- Targeting JSBackend
> -- Targeting MSP430
> -- Targeting Sparc
> -- Targeting NVPTX
> -- Targeting AVR
> -- Configuring done
> CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
>   The dependency target "llvm-xray" of target "check-all" does not exist.
> Call Stack (most recent call first):
>   CMakeLists.txt:906 (add_lit_target)
>
> CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
>   The dependency target "llvm-xray" of target "check-llvm-tools-sanstats"
>   does not exist.
> Call Stack (most recent call first):
>   cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
>   test/CMakeLists.txt:150 (add_lit_testsuites)
>
> [... hundreds or thousands of similar lines left out ...]
>
> CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
>   The dependency target "llvm-xray" of target
>   "check-llvm-codegen-mips-fast-isel" does not exist.
> Call Stack (most recent call first):
>   cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
>   test/CMakeLists.txt:150 (add_lit_testsuites)
>
>
> CMake Error at cmake/modules/AddLLVM.cmake:1174 (add_dependencies):
>   The dependency target "llvm-xray" of target
>   "check-llvm-transforms-instcombine" does not exist.
> Call Stack (most recent call first):
>   cmake/modules/AddLLVM.cmake:1226 (add_lit_target)
>   test/CMakeLists.txt:150 (add_lit_testsuites)
>
>
> -- Generating done
> -- Build files have been written to: /home/serenity/rust-avr/avr-rust/build/build/x86_64-unknown-linux-gnu/llvm/build
> thread 'main' panicked at '
> command did not execute successfully, got: exit code: 1
>
> build script failed, must exit now', /home/serenity/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.22/src/lib.rs:617
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
>         finished in 9.631
> Build completed unsuccessfully in 0:01:09
> make: *** [Makefile:24: all] Error 101
>
> real    1m9.769s
> user    1m59.131s
> sys     0m8.528s
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/avr-rust/llvm/pull/4#issuecomment-331624680>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHXUr0BeB5-PPOAlOVdR0t64UZzEqcBKks5slNpmgaJpZM4PgE23>
> .
>

2017-09-23 15:10 UTC, exscape commented
Huh, I indeed got it to build by removing the build dir *and* source dir, and re-fetching and re-adding my patch. Thanks!   
However, even *without* any of my changes, I get 5 test failures for AVR (plus 4 expected failures).  
Are these test failures actually also expected (i.e. not my fault 😄) ?

I compiled the source tree with my float fix, then ran the tests, and got the errors. After that, I removed the fix and recompiled LLVM (and verified that the recompile had an effect, i.e. I'm not running stale code or tests) and re-ran the tests, on commit a5e4ec2528e4305, and they still fail. 
The failures are:

```
[serenity@arch build]$ llvm-lit -q ~/rust-avr/avr-rust/rust/src/llvm/test/CodeGen/AVR
llvm-lit: /home/serenity/rust-avr/avr-rust/rust/src/llvm/test/lit.cfg:332: note:
  Did not find llvm-xray in
  /home/serenity/rust-avr/avr-rust/build/build/x86_64-unknown-linux-gnu/llvm/build/./bin
FAIL: LLVM :: CodeGen/AVR/call.ll (18 of 114)
FAIL: LLVM :: CodeGen/AVR/directmem.ll (31 of 114)
FAIL: LLVM :: CodeGen/AVR/pseudo/LDDWRdYQ.mir (98 of 114)
FAIL: LLVM :: CodeGen/AVR/pseudo/LDDWRdPtrQ.mir (110 of 114)
FAIL: LLVM :: CodeGen/AVR/varargs.ll (113 of 114)
********************
Failing Tests (5):
    LLVM :: CodeGen/AVR/call.ll
    LLVM :: CodeGen/AVR/directmem.ll
    LLVM :: CodeGen/AVR/pseudo/LDDWRdPtrQ.mir
    LLVM :: CodeGen/AVR/pseudo/LDDWRdYQ.mir
    LLVM :: CodeGen/AVR/varargs.ll

  Unexpected Failures: 5
```

2017-09-23 16:21 UTC, exscape commented
So I have a working test, but the .ll file is almost 1000 lines... 3 times greater than any other AVR CodeGen test.  
Can I cut it down somehow, without manually rewriting a IR file to trigger this bug (since I'm not sure how to trigger it, exactly)?

2017-09-23 17:57 UTC, exscape commented
Never mind, I guess! 😄  
I compiled a similar program to IR from C (using x86_64 Clang), and edited that (much smaller) IR to "port" it to AVR, cut out cruft, and cause the same bug. I guess I had some luck, because it was fairly easy to find array size values that triggered it!

The added test fails on the previous HEAD, and succeeds now.

2017-09-23 19:32 UTC, exscape commented
Apologies for the spam today, but I do believe I'm finished now.  
I updated the test code so that one test case generates both invalid std and invalid ldd instructions, and it tests for both.

2017-09-24 01:06 UTC, shepmaster commented
@exscape you can give [bugpoint a shot](https://github.com/avr-rust/rust/wiki#reduce-the-testcase).

2017-09-24 01:20 UTC, dylanmckay commented
@exscape there's no spam, don't worry about that, be as verbose as you please :)

Agree with @shepmaster that bugpoint is the easiest/fastest way to reduce the testcase, although I think you've already reduced it massively in cb0f156aa0eac5ed3163172161450e7f3724b560

2017-09-24 01:23 UTC, dylanmckay requested changes
Looking good, two minor testcase nitpicks and then I'm happy to merge

2017-09-24 01:23 UTC, dylanmckay commented on test/CodeGen/AVR/std-ldd-immediate-overflow.ll
> +; Function Attrs: argmemonly nounwind
This comment can be omitted, I _think_ it is machine-readable, but it is inferred if omitted IIRC

2017-09-24 01:23 UTC, dylanmckay commented on test/CodeGen/AVR/std-ldd-immediate-overflow.ll
> +define i32 @std_ldd_overflow() #0 {
The `#0` metadata reference can be removed

2017-09-25 19:47 UTC, exscape commented
Hm, I'm not sure how the Github review system works (i.e. whether you were notified), but I did update the pull request to implement your requested changes. :)

On an entirely off-topic note, is there some place (IRC/discord/forum/...) to discuss avr-rust more generally? I sometimes spend a full day figuring something out, only to find it could've been done in minutes if I'd only known the right tool existed.

2017-09-25 19:51 UTC, shepmaster commented
> is there some place (IRC/discord/forum/...) to discuss avr-rust more generally

Our [gitter channel](https://gitter.im/avr-rust/Lobby) should be linked from the avr-rust README.

2017-09-25 19:55 UTC, dylanmckay commented
> Hm, I'm not sure how the Github review system works (i.e. whether you were notified)

I believe that it doesn't notify about new commits, but it will for code review points you comment on.

Will take a look at this again within the next few days, likely sooner

2017-10-02 03:20 UTC, dylanmckay approved these changes
Didn't even notice the new commit!

This looks good to me, I'll merge this later tonight, commit it to LLVM master, and get it merged into 5.0.1

2017-10-04 09:54 UTC, dylanmckay commented
Upstreamed in [r314890](http://llvm.org/viewvc/llvm-project?view=revision&revision=314890)

2017-10-04 09:56 UTC, dylanmckay commented
The history has been rewritten after this branch was created.

I will cherry-pick this locally and push to master instead

2017-10-04 09:59 UTC, dylanmckay commented
Committed in da486df4dd76c1f9aa80e910b51c1543bc2dc1c7

2017-10-04 09:59 UTC, closed without merging

2017-10-04 10:11 UTC, dylanmckay commented
Have created a merge request to get this into LLVM 5.0.1 [here](https://llvm.org/PR34829).